GTCEuStartupEvents.registry('gtceu:tag_prefix', event => {
    const $BlockTags = Java.loadClass('net.minecraft.tags.BlockTags')
    const $AD_ModBlocks = Java.loadClass('earth.terrarium.ad_astra.common.registry.ModBlocks')

    TagPrefix.oreTagPrefix('moon_stone')
    .langValue('Moon %s Ore')
    .materialIconType(GTMaterialIconType.ore)
    .miningToolTag($BlockTags.MINEABLE_WITH_PICKAXE)
    .unificationEnabled(true)
    .generationCondition(ItemGenerationCondition.hasOreProperty)
    .registerOre(() => $AD_ModBlocks.MOON_STONE.get().defaultBlockState())

    TagPrefix.oreTagPrefix('mars_stone')
    .langValue('Mars %s Ore')
    .materialIconType(GTMaterialIconType.ore)
    .miningToolTag($BlockTags.MINEABLE_WITH_PICKAXE)
    .unificationEnabled(true)
    .generationCondition(ItemGenerationCondition.hasOreProperty)
    .registerOre(() => $AD_ModBlocks.MARS_STONE.get().defaultBlockState())

    TagPrefix.oreTagPrefix('venus_stone')
    .langValue('Venus %s Ore')
    .materialIconType(GTMaterialIconType.ore)
    .miningToolTag($BlockTags.MINEABLE_WITH_PICKAXE)
    .unificationEnabled(true)
    .generationCondition(ItemGenerationCondition.hasOreProperty)
    .registerOre(() => $AD_ModBlocks.VENUS_STONE.get().defaultBlockState())

    TagPrefix.oreTagPrefix('mercury_stone')
    .langValue('Mercury %s Ore')
    .materialIconType(GTMaterialIconType.ore)
    .miningToolTag($BlockTags.MINEABLE_WITH_PICKAXE)
    .unificationEnabled(true)
    .generationCondition(ItemGenerationCondition.hasOreProperty)
    .registerOre(() => $AD_ModBlocks.MERCURY_STONE.get().defaultBlockState())

    TagPrefix.oreTagPrefix('glacio_stone')
    .langValue('Glacio %s Ore')
    .materialIconType(GTMaterialIconType.ore)
    .miningToolTag($BlockTags.MINEABLE_WITH_PICKAXE)
    .unificationEnabled(true)
    .generationCondition(ItemGenerationCondition.hasOreProperty)
    .registerOre(() => $AD_ModBlocks.GLACIO_STONE.get().defaultBlockState())
})