ServerEvents.recipes(event => {
    event.remove({id: 'gtceu:primitive_blast_furnace/steel_from_charcoal_dust'})
    event.remove({id: 'gtceu:primitive_blast_furnace/steel_from_coal_gem_wrought'})
    event.remove({id: 'gtceu:primitive_blast_furnace/steel_from_charcoal_block_wrought'})
    event.remove({id: 'gtceu:primitive_blast_furnace/steel_from_coal_dust_wrought'})
    event.remove({id: 'gtceu:primitive_blast_furnace/steel_from_charcoal_block'})
    event.remove({id: 'gtceu:primitive_blast_furnace/steel_from_coal_block_wrought'})
    event.remove({id: 'gtceu:primitive_blast_furnace/steel_from_charcoal_gem_wrought'})
    event.remove({id: 'gtceu:primitive_blast_furnace/steel_from_coal_block'})
    event.remove({id: 'gtceu:primitive_blast_furnace/steel_from_coal_dust'})
    event.remove({id: 'gtceu:primitive_blast_furnace/steel_from_charcoal_dust_wrought'})
    event.remove({id: 'gtceu:primitive_blast_furnace/steel_from_charcoal_gem'})
    event.remove({id: 'gtceu:primitive_blast_furnace/steel_from_coal_gem'})
})