// GTCEuStartupEvents.registry('gtceu:machine', event => {
//     event.create('tree_growth_simulator', 'multiblock')
//         .rotationState(RotationState.NON_Y_AXIS)
//         .recipeType('tree_growth_simulator')
//         .appearanceBlock(() => Block.getBlock('kubejs:sterile_farm_casing'))
//         .recipeModifier(GTRecipeModifiers.ELECTRIC_OVERCLOCK.apply(OverclockingLogic.PERFECT_OVERCLOCK))
//         .pattern(definition => FactoryBlockPattern.start()
//             .aisle('#BBB#', '#BBB#', '#BBB#', '#BBB#')
//             .aisle('BBBBB', 'B###B', 'B###B', 'BGGGB')
//             .aisle('BBBBB', 'B###B', 'B###B', 'BGGGB')
//             .aisle('BBBBB', 'B###B', 'B###B', 'BGGGB')
//             .aisle('#BBB#', '#BEB#', '#BBB#', '#BBB#')
//             .where('E', Predicates.controller(Predicates.blocks(definition.get())))
//             .where('G', Predicates.blocks('gtceu:tempered_glass'))
//             .where('B', Predicates.blocks('kubejs:sterile_farm_casing').setMinGlobalLimited(5).or(Predicates.autoAbilities(definition.getRecipeTypes())))
//             .where('#', Predicates.air)
//             .build()
//         )
//         .shapeInfo(definition => MultiblockShapeInfo.builder()
//             .aisle('#BBB#', '#BBB#', '#BBB#', '#BBB#')
//             .aisle('BBBBB', 'B###B', 'B###B', 'BGGGB')
//             .aisle('BBBBB', 'B###B', 'B###B', 'BGGGB')
//             .aisle('BBBBB', 'B###B', 'B###B', 'BGGGB')
//             .aisle('#IOC#', '#BEB#', '#BBB#', '#BBB#')
//             .where('E', definition)
//             .where('G', GTBlocks.CASING_TEMPERED_GLASS)
//             .where('B', Block.getBlock('kubejs:sterile_farm_casing'))
//             .where('I', GTMachines.ITEM_IMPORT_BUS[1], Direction.NORTH)
//             .where('O', GTMachines.ITEM_EXPORT_BUS[1], Direction.NORTH)
//             .where('C', GTMachines.ENERGY_INPUT_HATCH[1], Direction.NORTH)
//             .where('#', Blocks.AIR)
//         )
//         .workableCasingRenderer(
//             new ResourceLocation('minecraft:block/acacia_log_top'), 
//             new ResourceLocation('gtceu:block/multiblock/implosion_compressor'), 
//             true
//         )
// })